### PR TITLE
Add fixture for wrong version in version dir

### PR DESCRIPTION
**Pull request by pwinckles**
Fixture for wrong version in a version directory

### CODE REVIEW

**Comment by zimeon** [comment]
```
(py38) simeon@RottenApple fixtures> ../ocfl-validate.py 1.0/bad-objects/E040_wrong_version_in_version_dir
[E040] OCFL Object root inventory head attribute doesn't match versions (got v2, expected v3) (see https://ocfl.io/1.0/spec/#E040)
INFO:ocfl.object:OCFL object at 1.0/bad-objects/E040_wrong_version_in_version_dir is INVALID
```

**Review by zimeon — APPROVED** [review]

**Comment by pwinckles** [comment]
Looking at your output, I realized that this fixture is actually not setup the way I want. I want the failure to be specifically related to a version directly claiming to be one version but the inventory in the directory claiming to be another. This is muddied in the fixture because the head version also comes into play.

I'm going to change it so that a non-head version's inventory does not match the expected version.

**Review by zimeon — CHANGES_REQUESTED** [review]
Temporarily un-approving to give Peter time to make the changes he proposes above

**Comment by pwinckles** [comment]
I updated the fixture so that the `v2` inventory is incorrect and the root inventory and `v3` inventories are fine.

**Comment by zimeon** [comment]
v2 inventory is now same as the valid v3, and thus incorrectly includes description of v3

**Review by zimeon — APPROVED** [review]

**Review by awoods — APPROVED** [review]

**Pull request merged**
