### PR TITLE
Add fixture for invalid padded version

### PR DESCRIPTION
**Pull request by pwinckles**
Fixture for invalid head version number zero-padding

### CODE REVIEW

**Review by zimeon — CHANGES_REQUESTED** [review]
I think this should be `E011`:
> 'The version number sequence must start at 1 and MUST be continuous without missing integers.'

instead of `E013` which is about operations and thus not really relevant to validation:
> `Operations that add a new version to an object must follow the version directory naming convention established by earlier versions.`

**Comment by pwinckles** [comment]
@zimeon You referenced `E011` but quoted `E010`. None of then really fit. The MUST in the quoted text is about _missing_ versions. There is no version missing here, just one that's invalid based on the padding that was used. I think `E013` fits better because the first 9 are zero-padded, but the 10th is not. `v10` in and of itself is valid, it is only invalid because it does not align with the prior versions.

**Comment by pwinckles** [comment]
Another thing that I like about `E013` is that it can be used for both a series like `v1`, `v02`, `v3` as well as a series like `v01`, `v02`, `v3`. All it cares about is that versions are consistently padded. Without `E013`, both of these example sequences would be considered valid because `E011` does not require consistency. It just requires that a zero-padded version starts with `v0`, which is the case.

**Comment by zimeon** [comment]
Oops, yes, I do mean `E011` even though I quoted `E010` by mistake.

I think part of my aversion to `E013` is that it is written in terms of operations on the object which the spec is explicitly not supposed to be about only "the object-at-rest" (https://ocfl.io/1.0/spec/#note). 

I think _"Operations that add a new version to an object must follow the version directory naming convention established by earlier versions. "_ should be rewritten to something like _"The version naming convention MUST be consistent across all versions."_ --> https://github.com/OCFL/spec/issues/541

Having said that, and imagining a rewrite like the above, I'd be OK to go with both `E011` and `E013`.

**Comment by pwinckles** [comment]
I renamed the directory to `E011_E013_invalid_padded_head_version`

**Review by zimeon — APPROVED** [review]

**Review by awoods — APPROVED** [review]

**Comment by srerickson** [comment]
I know it's been a while since fixture was merged but I have a question that relates to this discussion. My validator returns E012 for this fixture:

> E012: "All version directories of an object must use the same naming convention: either a non-padded version directory number, or a zero-padded version directory number of consistent length."

I like E012 here; I'm just wondering why it wasn't included/considered.

**Comment by pwinckles** [comment]
@srerickson `E012` seems good to me too. I don't remember exactly what my original thoughts were, but I assume that I originally picked `E013` because the text does not reference "version directories" and I dislike referencing directories while validating an inventory.

Since this PR, the text of `E013` changed and it appears to be a redundant sentence that reiterates the requirement of `E012`, though does not mention directories. :P

> All version directories of an object MUST use the same naming convention: either a non-padded version directory number, or a zero-padded version directory number of consistent length. The version naming convention MUST be consistent across all versions.

**Comment by srerickson** [comment]
thanks @pwinckles 

> I assume that I originally picked E013 because the text does not reference "version directories" and I dislike referencing directories while validating an inventory.

That makes sense. I chose E012 because I'm validating version directory names directly (i.e., before the inventory contents). The new E013 looks like it should cover both scenarios so it doesn't matter which comes first (inventory or file system). I'll switch to that.

**Comment by pwinckles** [comment]
It does seem that the fixture should perhaps be updated to indicate that `E012` also works.

**Pull request merged**
