### PR TITLE
Add fixture for skipped versions

### PR DESCRIPTION
**Pull request by pwinckles**
Fixture for skipped version numbers

### CODE REVIEW

**Review by zimeon — CHANGES_REQUESTED** [review]
Fixture looks good but I don't think `E044` is right:
> This block MUST have the key of versions within the inventory, and it must be a JSON object.

I think `E010` makes more sense:
> The version number sequence must start at 1 and MUST be continuous without missing integers.

**Comment by zimeon** [comment]
My validator reports `E010` but also a spurious `E040` because after finding the version gap it uses `v1` as the `head`
```
(py38) simeon@RottenApple fixtures> ../ocfl-validate.py 1.0/bad-objects/E044_skipped_versions/
[E010] OCFL Object root inventory versions block includes an out-of-sequence version (see https://ocfl.io/1.0/spec/#E010)
[E040] OCFL Object root inventory head attribute doesn't match versions (got v8, expected v1) (see https://ocfl.io/1.0/spec/#E040)
INFO:ocfl.object:OCFL object at 1.0/bad-objects/E044_skipped_versions/ is INVALID
```

**Comment by pwinckles** [comment]
I see where you're coming from and I will update it next week. This partly comes down to validation strategy, as you've talk about before, and partly comes down to my unease with the validation codes.

I use the root inventory as the source of truth for the object, as you've mentioned elsewhere that you do as well. If the root inventory fails to validate, I do not look at anything else because I do not know what is true. If the root does validate, then everything is on the table.

The annoyance with this approach is that the OCFL spec, and therefore validation codes, were _not_ written in such a way that the root inventory is considered the source of truth. Instead, it most commonly treats the files on disk as the source of truth. For example, version numbers are defined in terms of directory names and the most recent version of the object is "the directory name with the highest version number".

These rules then must be inferred onto the structure of the inventory, which means that you return errors about files on disk for inventory problems. I personally do not like this, and tried to avoid it as much as possible.

**Comment by pwinckles** [comment]
I renamed the directory `E010_skipped_versions`

**Review by zimeon — APPROVED** [review]

**Review by awoods — APPROVED** [review]

**Pull request merged**
