### PR TITLE
Add fixture for version inventory digest mismatch

### PR DESCRIPTION
**Pull request by pwinckles**
Fixture for a version inventory file not matching its expected digest value

### CODE REVIEW

**Comment by zimeon** [comment]
```
ocfl-validate.py 1.0/bad-objects/E060_version_inventory_digest_mismatch/
[E060] Mismatch between actual and recorded inventory digests for v1/inventory.json (calcuated 5bf08b6519f6692cc83f3d275de1f02414a41972d069ac167c5cf34468fad82ae621c67e1ff58a8ef15d5f58a193aa1f037f588372bdfc33ae6c38a2b349d846 but read cb7a451c595050e0e50d979b79bce86e28728b8557a3cf4ea430114278b5411c7bad6a7ecc1f4d0250e94f9d8add3b648194d75a74c0cb14c4439f427829569e from v1/inventory.json.sha512) (see https://ocfl.io/1.0/spec/#E060)
[E064] Object root inventory and copy in last version MUST be identical but are not (inventory.json and v2/inventory.json) (see https://ocfl.io/1.0/spec/#E064)
[W011] OCFL Object version metadata 'message' for v1 in v1 inventory does not match that in root inventory (see https://ocfl.io/1.0/spec/#W011)
INFO:ocfl.object:OCFL object at 1.0/bad-objects/E060_version_inventory_digest_mismatch/ is INVALID
```

```
> diff 1.0/bad-objects/E060_version_inventory_digest_mismatch/inventory.json 1.0/bad-objects/E060_version_inventory_digest_mismatch/v1/inventory.json
5c5
<   "head": "v2",
---
>   "head": "v1",
20,34c20
<       "message": "Simple example",
<       "user": {
<         "name": "tester",
<         "address": "mailto:tests@example.com"
<       }
<     },
<     "v2": {
<       "created": "2021-03-31T08:51:24.084110226-05:00",
<       "state": {
<         "24f950aac7b9ea9b3cb728228a0c82b67c39e96b4b344798870d5daee93e3ae5931baae8c7cacfea4b629452c38026a81d138bc7aad1af3ef7bfd5ec646d6c28": [
<           "test.txt",
<           "test-2.txt"
<         ]
<       },
<       "message": "Simple example v2",
---
>       "message": "Changed!",
```

**Review by zimeon — CHANGES_REQUESTED** [review]
I think this could easily be simplified to generate only error `E060` by making sure that v2 and root inventories match, and by making v1 an appropriate subset inventory with just a mismatching digest file

**Comment by pwinckles** [comment]
@zimeon This fixture was intended to test what happens when the most recent version of an inventory does not match its digest as well as when an earlier version does not match its digest, same problem with slightly different behaviors. It is true that there is an additional `E064` error in the case of the most recent inventory. Personally, I would rather just add that error to the directory name than split them up, but a case could be made for splitting them.

The warning doesn't bother me, there are other fixtures with warnings, and I think makes the test feel authentic. That is to say, the reason that the `v1` inventory does not match its digest is because someone modified the inventory's message after it was written to disk and did not update the sidecar.

**Comment by pwinckles** [comment]
That said, there is also this fixture, https://github.com/OCFL/fixtures/pull/75, so perhaps I should remove the current version mismatch here.

**Comment by pwinckles** [comment]
I removed the digest mismatch for `v2`

**Review by zimeon — APPROVED** [review]

**Review by awoods — APPROVED** [review]

**Pull request merged**
