### PR TITLE
Further explain layout of fixtures in README.md

### PR DESCRIPTION
**Pull request by malakai97**
Cleans up readme language, text wrapping, and notes the relationship
between some fixtures that are represented in both the objects and
content directories.

### CODE REVIEW

**Comment by malakai97** [comment]
Can I ask why? Markdown is meant to be human readable; the additional newlines are not rendered.

**Comment by zimeon** [comment]
Maintaining line wraps is one more task and has little or no benefit

**Comment by malakai97** [comment]
applied

**Comment by zimeon** [comment]
Thanks @malakai97 !

**Pull request merged**
